# 1: kinect camera (default)
# 2: input file, parameter input_source must be specified
input: 1
#input_source: "../data/compressed_1611499557.dat"
input_source: "C:\Projects\cdp_tests\data\u1611612545.dat"