# 1: kinect camera (default)
# 2: input file, parameter input_source must be specified
input: 2
input_source: "C:\Projects\cdp_tests\data\1611710996_u_quitegood"

#task_thresholds_minX: -10.0f
#task_thresholds_maxX: 10.0f
#task_thresholds_minY: -10.0f
#task_thresholds_maxY: 10.0f
#task_thresholds_minZ: 0.0f
#task_thresholds_maxZ: 10.0f
#task_countour_detector_threshold1: 0.08f
#task_countour_detector_threshold2: 1.0f

task_thresholds_minX: -0.8f
task_thresholds_maxX: 0.4f
task_thresholds_minY: -0.1f
task_thresholds_maxY: 0.6f
task_thresholds_minZ: 1.9f
task_thresholds_maxZ: 2.4f
task_countour_detector_threshold1: 0.7f
task_countour_detector_threshold2: 1.0f