# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ./KinectManager_Windows.h \
    ./vertex.h \
    ./MainWindow.h
SOURCES += ./KinectManager_Windows.cpp \
    ./main.cpp \
    ./MainWindow.cpp
FORMS += ./main_window.ui
RESOURCES += resources.qrc
