# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = app
TARGET = cdp_tests
DESTDIR = ./debug
CONFIG += debug console
DEFINES += _CONSOLE _UNICODE _ENABLE_EXTENDED_ALIGNED_STORAGE WIN64
LIBS += -L"$(SolutionDir)../cdp/Externals/OpenCV/lib" \
    -L"../../../cdp/Externals/Kinect v2.0/lib" \
    -l%(AdditionalIncludeDirectories) \
    -lKinect20 \
    -lopencv_world410d \
    -lopengl32 \
    -lglu32
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += debug
UI_DIR += .
RCC_DIR += .
include(cdp_tests.pri)
